#!/bin/bash

if [ $# -lt 1 -o $# -gt 2 ]; then
  echo "ERROR: Invalid number of input parameters."
  echo
  echo "Usage `basename $0` <Data-Set-Name> [<Config-Name>]"
  echo "   where,"
  echo "     <Data-Set-Name> is the main data type."
  echo "          Example: Reuters, Bloomberg, Verint"
  echo "     <Subset-Name> is subset configuration to process"
  echo "     For example, \"Transform\", \"Raw\", etc."
  echo

  exit 1
fi

# Setup Environment for specific DATA_SET and SUBSET_NAME (if any).

export DATA_SET="$1"
export SUBSET_NAME="$2"

. `dirname $0`/config/envsetup

# Make sure we have the core configuration files.
if [[ ( ! -f "${TOOL_CONFIG}/comet.properties" )
     || ( ! -f "${TOOL_CONFIG}/generator${CONFIG_POSTFIX}.properties" )
     || ( ! -f "${TOOL_CONFIG}/scanner${CONFIG_POSTFIX}.properties" )
     || ( ! -f "${TOOL_CONFIG}/log4j2.xml" ) ]]; then
   echo "ERROR: Invalid <Config-Name> parameter or missing configuration files."
   echo

   exit 1
fi

#Cleanup any possible stop file
rm -f ${COMET_STOP_FILE} > /dev/null

# This constant defines the class path entries for the custom modules that will
#   do the metadata processing. This line must be modified in order to pick up
#   the java entry points to these modules.
CUSTOM_MODULES=${TOOL_LIBS}/Rabobank.jar

CLASSPATH=${COMET_LIBS}/COMET.jar:${COMET_LIBS}/HCPAPIHelpers.jar
CLASSPATH=${CLASSPATH}:${COMET_LIBS}/httpcore-4.2.4.jar:${COMET_LIBS}/httpclient-4.2.5.jar:${COMET_LIBS}/commons-codec-1.6.jar:${COMET_LIBS}/commons-logging-1.1.1.jar
CLASSPATH=${CLASSPATH}:${COMET_LIBS}/log4j-api-2.0.2.jar:${COMET_LIBS}/log4j-core-2.0.2.jar
CLASSPATH=${CLASSPATH}:${COMET_LIBS}/saxon9he.jar
CLASSPATH=${CLASSPATH}:${CUSTOM_MODULES}
export CLASSPATH

DEFINES="-Dlog4j.configurationFile=${TOOL_CONFIG}/log4j2.xml -Dcom.hds.hcp.tools.comet.properties.file=${TOOL_CONFIG}/comet.properties -Dcom.hds.hcp.tools.comet.scanner.properties.file=${TOOL_CONFIG}/scanner${CONFIG_POSTFIX}.properties -Dcom.hds.hcp.tools.comet.generator.properties.file=${TOOL_CONFIG}/generator${CONFIG_POSTFIX}.properties -Dnl.rabobank.comet.util.regionmapper.properties.file=${TOOL_CONFIG}/RegionMapper${CONFIG_POSTFIX}.properties -Dnl.rabobank.comet.item.properties.file=${TOOL_CONFIG}/item.properties -Dnl.rabobank.comet.util.fileprefixmapper.properties.file=${TOOL_CONFIG}/FilePrefixMapper${CONFIG_POSTFIX}.properties"

#echo "DEFINES=$DEFINES"

java ${DEFINES} com.hds.hcp.tools.comet.CometMain 

#Cleanup any possible stop file
rm -f ${COMET_STOP_FILE} > /dev/null

exit $?
